


## When is the project due?

- The official project deadline is Friday, April 12th.
- You are encouraged to finish the project by Wednesday, April 10th. You will have an opportunity to present your project.
- This is voluntarily but operates under the "it can only help you" rule: if your presentation helps to clarify the contributions or challenges of your project, this may positively affect your grade.^[In particular, presenting your project can help you increase your "relevance to class themes" score, as I will ask questions and give you a chance to further demonstrate engagement with our key themes.]

## Extensions?

If you believe you can make major improvements with some extra time, you can write an "extension" plan at least a week in advance (i.e. by April 5th) detailing how your group will use the following time (between 1-5 days). 

This should be structured much like an email or presentation you might give your boss explaining why a feature needs an extra week of dev time (something that may happen in your career!)

## Warning!

Barring exceptional circumstances, if you have not asked for an extension by the 5th, whatever you turn in on April 12th will be graded.

## How is the class project graded?

Group-based scaling: I've mentioned in class that larger groups will higher overall expectations for what the project accomplishes.

In practice, this will be implemented based an assessment of "artifact quality" and based on your report's "contribution statements". You should describe what everyone did and provide evidence that everyone did something.

## Expectations


More concretely, we will use the following rubric/process to assign grades to the projects. Remember that a goal of the loose project guidelines is so that you can make something that will look good on your portfolio based on your own career or personal interests. This will be a motivating theme in grading -- could the project impress a potential employer?

## 

You are expected to do some degree of self or collaborative learning as part of the project. You may need to try out libraries we didn't use directly during class time or read work that wasn't assigned. If you are only engaging with course materials, this is enough for our quizzes, but probably not enough for the project.


## Report Rubric

- Abstract 	2 points
- Visual Abstract 	2 points
- Introduction 	4 points
- Related Work 	4 points
- Methods 	4 points
- Results 	4 points
- Discussion 	8 points
- Connection to class themes 	4 points
- Overall artifact quality 	8 points

## Report Rubric

- Abstract, Visual Abstract are tier 1
- Intro, RW, Methods, Results, Connection to Class themes are tier 2
- Discussion and Overall Artifact Quality are tier 3


## Abstract: 2 points

Summarize the key contribution of your project. It should be understandable to all of your classmates, and at least partially understandable to your peers from across a variety of disciplines.

Marking scheme: 
- 2/2 for clear concise project that explains what your project does and why you were motivated to do it. 
- 1/2 for abstract that is difficult to read, is vague, or doesn't motivate the work. 
- 0/2 for abstract that is very vague or missing.

## Visual Abstract: 2 points

Create a figure or diagram that summarizes the key contribution of your project.

Same marking scheme as abstract.

## Introduction: 4 points

State the problem your project solves. You should cite some motivating work.

You will not be graded based on how important I think your topic is, but based on the motivation, evidence, and reasoning. It's possible to pick something I really like but not motivate it well!

## Introduction marking scheme
- 4/4 for an intro that clearly states the problem your project wants to solve and provides evidence and reasoning for why this project can achieve its stated goal.
- 2/4 for intro that provides some motivation but lacks evidence.
- 0/4 for intro that is very vague, underdeveloped, or missing.

## Related work: 4 points

You should conduct a literature review of related work. This does not need to be restricted to peer-reviewed academic works or class readings. You can, and should, cite anything that helped you work on the project or serves as a point of comparison, including software libraries on GitHub, pre-prints on arXiv, blog posts from ML researchers, etc. You should be able to find 3-4 references, at least one of which is an academic work and itself provides upstream / "classics" in the subfield of your choice.

## Methods / What you did: 4 points

You should describe what you did. You are encouraged to find and cite an exemplar paper in order to help you structure your Methods section.

If you are unable to find an exemplar paper, please let me know!

## Results / What you produced: 4 points

This section will also vary quite a bit based on your project. You are encouraged to find and cite an exemplar paper here, as well.

## Discussion: 8 points

You can earn up to 8 points for discussing the implications of your project and especially potential lines of future work that incorporate a data-centric or human-centric lens. This section has a large point total because it is your change to show your engagement with course materials and concepts. You do not need to *only* discuss course readings or quote from course materials, but to earn a high score you should demonstrate engagement with course themes.

## Discussion marking scheme

- 8/8 for a Discussion section that situates the project with some subdomain of human-centered or data-centered machine learning
- 4/8 for a Discussion section that makes some connections to course themes, but is underdeveloped in some aspects
- 0/8 for a Discussion section that engages only superficially with course themes, is very vague in dusicussing future work, or is missing.

## Connection to class themes: 4 points

Does your project show engagement with some of the frameworks for thinking we've discussed in the class? If I saw this project in your portfolio, would it give me confidence in your ability to work on "human-centered" or "data-centered" projects?

Across all sections, of the report, you can earn up to 10 points for demonstrating connections to class themes.

## Overall artifact quality: 8 points

You will also earn up to 8 points for producing high quality artifacts -- this might be code, UI design mock-ups, an actual interface, or a very well formatted report.

You should include at the end of your report a contribution statement describing specifically how each group member contributed to each section of the project and each artifact.

You will also turn in (via zip file or web link) your project artifacts (code, design files, data outputs, other artifacts, etc.). You are encouraged to create a public GitHub repository and just put the link in your report PDF. This will make it easier to share with others as well.


## What do I turn in?

Required: a report as PDF.

Optional: include a web link to your project materials (e.g. a GitHub link).

Optional: include a a zip file with project materials.

Optional: Present your project during the final week of class.
